# Generated by Django 6.0.3 on 2026-06-15 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_upgrade_learning_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabularyquestion',
            options={'ordering': ['category', 'difficulty', 'id']},
        ),
        migrations.RenameField(
            model_name='conversationsession',
            old_name='title',
            new_name='custom_topic',
        ),
        migrations.RenameField(
            model_name='conversationsession',
            old_name='feedback',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='vocabularyquestion',
            old_name='topic',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='vocabularyquestion',
            old_name='correct_answer',
            new_name='correct_option',
        ),
        migrations.RenameField(
            model_name='vocabularyquestion',
            old_name='level',
            new_name='difficulty',
        ),
        migrations.RemoveField(
            model_name='grammarcheck',
            name='errors',
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='fluency_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='grammar_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='vocabulary_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='topic',
            field=models.CharField(choices=[('Daily Conversation', 'Daily Conversation'), ('Travel', 'Travel'), ('Education', 'Education'), ('Job Interview', 'Job Interview'), ('Business', 'Business'), ('Restaurant', 'Restaurant'), ('Shopping', 'Shopping'), ('Custom', 'Custom')], max_length=100),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grammarcheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GrammarMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistake_type', models.CharField(default='General Grammar', max_length=100)),
                ('original', models.CharField(blank=True, max_length=255)),
                ('correction', models.CharField(blank=True, max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('grammar_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='core.grammarcheck')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vocabularyquestion')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.quizattempt')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('mistake_count', models.PositiveIntegerField(default=1)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_mistakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mistake_count', 'word'],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
