# Generated by Django 6.0.3 on 2026-06-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_vocabularyquestion_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VocabularyMistake',
        ),
    ]
